require_relative 'group'
require_relative 'product'
require_relative 'sale'
require_relative 'shopee'
require_relative 'queue_for_search'
require_relative 'queue_for_cate'
require_relative 'hot_cate'
require_relative 'hot_keyword'
